### ISSUE TITLE
Fully transparent user info menu

### ISSUE THREAD

**Issue by luxidoptera** [puckzxz/NotAnotherAnimeTheme#145]
Hey it's me again, your regular "I refreshed and now there's a bug" messenger! I woke up today to find the user info menus one would see upon clicking on a user's name 100% transparent. This looks fine if there's nothing behind the box, but if there is, the problem becomes very apparent:

![image](https://user-images.githubusercontent.com/15697751/67941258-422d0b00-fba3-11e9-8e9a-2710ce44120e.png)

I have a habit of reflexively clicking to show info menus, so I was quick to notice this and would love to see it fixed. As usual, I'm on PTB.

**Comment by puckzxz** [comment]
If you don't have the `--user-popup-background` option in your theme file I would recommend updating to the latest version of the theme file, version `2.1`, since that will give you control over the transparency.  I have added a backwards compatibility patch in case a user has an older version of the theme file that doesn't have the `--user-popup-background` option, it will use the `--main-transparency` option instead.
