### ISSUE TITLE
META not found.

### ISSUE THREAD

**Issue by tkh123** [puckzxz/NotAnotherAnimeTheme#26]
When i put in the newest version of this theme into the discord theme folder and when i start discord, it said META not found, is it related to the new version of the BetterDiscordApp?

**Comment by ImVexed** [comment]
A new discord update yesterday is breaking BetterDiscord installs.  If your BetterDiscord is no longer loading after updating then you can reinstall by downloading the BandagedBD.exe from this link here https://github.com/rauenzi/BetterDiscordApp/releases/latest

**Comment by ImVexed** [comment]
This issue is 16 days old, what have you tried since? Or are you referring to the update discord pushed yesterday that broke every available theme?

Either way, the steps forward are to install Bandaged Discord @:
https://github.com/rauenzi/BetterDiscordApp/releases/latest
And then select one of the new updated theme files from the repository.

**Comment by ImVexed** [comment]
Its come to my attention that you were downloading the HTML instead of the CSS and expected it to work. 

GitHub issues are not the correct place for user support, you can seek help there.
